language: java
jdk:
- oraclejdk8
deploy:
  provider: bintray
  file: "descriptor.json"
  skip_cleanup: true
  on:
    tags: true
  user:
    secure: "vX9hdWdZtyKs/bicYujQBhSHbi1I60CtiO/tVNJ04/mbS3MhsPWStuUOw3lQWnsjOAIcBC+zta+QgRuHwGhA8VJm/tfZcEX3bekEiw+kpXFP2nL31IR18efvcsGp9c17u+7uk4gOsKcqBmRja9NzIrghdtQTFLiLu4hnrqdbvekMiVkdv3zSnAZ8L7IEKA5EJdC1dZC3sezjdIkd3pze8bd/wIYgmHH3rwHXQ02vGwWxX8eJOA3LCQ26HSlccYsDmuu1dEwDdPYajOKCSiB0YSdlDFJ982jpO/+6yzV+NaYbR9FdcNuNDGHKZTMcyud3pNBxshD82+sJeSmqXHvoBMGrGDdxLWcRwnt0wiUkTLw2c7BdD3PJU+v0L+bshOr2HerAO3WwYqijEUr02WVctibUQaDeuy2z+VVIK/5YnY7i8wU4eT5Om8f+eaRJ+IJAz7J9BGNqS/Wd0N5tANDNfGUUuF8aSkMlxs4ySpYIl10gQRCwpd4gz+ZJxX9o0p6vJfrLRvpY17bE4Ft2pjM9sZl5oViteZnfMGsE99caJy3Y7Z0jI372m7LnVrTuvY13eH7NutAcgpX2UKHUOCdaj1857F6G8JscjE70WPkQJz0LKOyq38IRzKlsvVLJ/9k/ATugoxPRosVXJzNOZzjj7yc8BhE3o4JTPx1pPnTJQaE="
  key:
    secure: "p9MDx8wag9dSQ89zZfZ8hnqGhFJUP/Uz+qAlpK+xlsUjWbqayMVLigMIjwD4uJP3XW180DHS7WnMyLs1mJILechRZG1bXdXp6Nm33YkrEKxDkPJ8B5CyRpVBb3azgXsjVzIEeshATNAo/xIigkP/4mqGI9xaniGFTRErk6K/0UN8A0JmBwPi7nmK/HN2uC8n4KVUb8GBfzcwPYdprCFNHjclEbmQOZyPXUVQzRg/Gsuu1nCML3RArfVA0+Vbzsfomzd7Vyqp28AYZ0cQ8NdPOm5dmAEzVaJ1qGiHSYpVT6QGaSHvcdlmh8swSws8jeOa+tu516go0lSmnVe5YV/eGR2q/iFVcsj9iy0I/1k10jWw/eHOT4xmzRhidHS3Ou/MQeL1D3DEXqLuiNbQXuEr/ZGoGRy8Vm2Ygvw+2LJhaZf0FcQYlw9dQKzpP8tvFBnQ/p0BUQRuUtanj+gPqOzeklaJolXzCbTRquKKMLGGow+9QKrhgYjTF4/chtWQSHT6St7YtyWAkILZOJRFcS6DNK4AqlpNxRUn+MSXzlZgivvBruF4qr5E0nPVN7ZCO7tzmgse1KmUHd6J7TalQ3Y+cAS1QMcsp+hytCQqh0Bzc366kYvPOapYbQjsj6i+cbZ0lZSgaWA6O8/r5/ONhKS9ocZAfZRfAPrHFhq4JaN5okE="